// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyeyousglejolnyazres.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5ZXlvdXNnbGVqb2xueWF6cmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjI0MTcsImV4cCI6MjA2OTYzODQxN30.RCieJiZ-YUsO8QIticd_YN2e1zLGqQfnYMhPnObHMCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});